language: python
python:
  - "3.6"
cache: pip
install:
  - pip install coverage
  - pip install colorama
script:
  - python3 -m unittest
  - coverage run test_rpn.py
  - coverage report -m
